name: CI
on:
  push:
    # branches: ['main']
  pull_request:
    # branches: ['main']
jobs:
  specs:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        ruby-version: ['2.7', '3.0', '3.1', 'head']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup phlex
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./phlex
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Setup phlex-rails
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          working-directory: ./phlex-rails

      - name: phlex tests
        run: bundle exec sus
        working-directory: ./phlex

      - name: phlex type check
        run: bundle exec solargraph typecheck --level typed
        working-directory: ./phlex

      - name: phlex rubocop
        run: bundle exec rubocop

      - name: phlex-rails tests
        working-directory: ./phlex-rails
        run: bundle exec sus

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install JavaScript dependencies
        run: npm install

      - name: Build docs
        run: bundle exec docs/build.rb
